function [com] = calculate_com()

global robot RShoulderPitch LShoulderPitch RShoulderRoll LShoulderRoll ...
    LHipRoll LHipPitch LKneePitch LAnklePitch LAnkleRoll ...
    RHipRoll RHipPitch RKneePitch RAnklePitch RAnkleRoll ...
    RHipYawPitch LHipYawPitch ...
    RAnkleRoll_end_point LAnkleRoll_end_point RAnklePitch_end_point ...
    LHipYawPitch_end_point RHipYawPitch_end_point ...
    LKneePitch_end_point RKneePitch_end_point




end